services:
  # A web service for the dashboard application
  - type: web
    name: housing-data-dashboard
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn app:server --timeout 120"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: GOOGLE_MAPS_API_KEY
        generateValue: true
      - key: MAP_DEBUG_MODE
        value: "true"  # Enable map debugging to help diagnose issues
      - key: DASHBOARD_ENV
        value: "production" # Set to production for Render to potentially disable Dash debug mode
    healthCheckPath: / 